import type { User, Transaction, AreaPrep } from "./types"

export const USERS: User[] = [
  { id: "U-SALES", name: "ليث المبيعات", role: "sales", phone: "0790000001" },
  { id: "U-DISP", name: "خالد الموزّع", role: "dispatcher", phone: "0790000002" },
  { id: "U-INS1", name: "عمر (فني مد)", role: "installer", area: "حي الصحة", phone: "0790000003" },
  { id: "U-INS2", name: "سامي (فني مد)", role: "installer", area: "حي الصحة", phone: "0790000004" },
  { id: "U-SPL1", name: "ياسر (فني لحام)", role: "splicer", area: "حي الصحة", phone: "0790000005" },
  { id: "U-SPL2", name: "محمود (فني لحام)", role: "splicer", area: "حي الصحة", phone: "0790000006" },
  { id: "U-ACT", name: "نور (تفعيل)", role: "activator", phone: "0790000007" },
  { id: "U-SUP", name: "أحمد مشرف المنطقة", role: "supervisor", area: "حي الصحة", phone: "0790000008" },
  { id: "U-ADM", name: "الإدارة العليا", role: "admin", phone: "0790000009" },
]

// مركز حي الصحة - إربد
export const AREA_CENTER: [number, number] = [32.5556, 35.85]

// حدود المنطقة المراد خدمتها (المضلع الأخضر)
export const AREA_BOUNDARY: [number, number][] = [
  [32.5612, 35.8418],
  [32.5628, 35.8512],
  [32.5585, 35.8588],
  [32.5512, 35.8602],
  [32.5468, 35.8538],
  [32.5478, 35.8442],
  [32.5535, 35.8398],
]

function hist(byName: string, action: string, daysAgo: number) {
  const d = new Date()
  d.setDate(d.getDate() - daysAgo)
  return { id: `H-${Math.random().toString(36).slice(2, 8)}`, at: d.toISOString(), byName, action }
}

export const INITIAL_TRANSACTIONS: Transaction[] = [
  {
    id: "INT086795618",
    customerName: "أحمد خالد زيدان الجمل",
    phone: "0795957073",
    nationalId: "9981023455",
    area: "إربد / حي الصحة",
    service: "New Network Access",
    month: "May-26",
    lat: 32.5571,
    lng: 35.8456,
    status: "new",
    createdAt: new Date().toISOString(),
    deviceType: "ONT - Huawei HG8145V5",
    speed: "100 Mbps",
    createdById: "U-SALES",
    createdByName: "ليث المبيعات",
    materials: [],
    feedback: [],
    history: [hist("ليث المبيعات", "إنشاء العقد وإصدار رقم الاشتراك", 1)],
  },
  {
    id: "INT086795742",
    customerName: "منى سليم العمري",
    phone: "0796123440",
    nationalId: "9985512300",
    area: "إربد / حي الصحة",
    service: "New Network Access",
    month: "May-26",
    lat: 32.5598,
    lng: 35.8489,
    status: "new",
    createdAt: new Date().toISOString(),
    deviceType: "ONT - Huawei HG8145V5",
    speed: "100 Mbps",
    createdById: "U-SALES",
    createdByName: "ليث المبيعات",
    materials: [],
    feedback: [],
    history: [hist("ليث المبيعات", "إنشاء العقد وإصدار رقم الاشتراك", 1)],
  },
  {
    id: "INT086795810",
    customerName: "يوسف عبدالله الشريدة",
    phone: "0798445512",
    nationalId: "9990012345",
    area: "إربد / حي الصحة",
    service: "Fiber Upgrade",
    month: "Apr-26",
    lat: 32.5543,
    lng: 35.8512,
    status: "laid",
    createdAt: new Date().toISOString(),
    deviceType: "ONT - Huawei HG8145V5",
    speed: "100 Mbps",
    createdById: "U-SALES",
    createdByName: "ليث المبيعات",
    assignedInstallerId: "U-INS1",
    materials: [
      { id: "M1", name: "كابل Drop", quantity: 60, unit: "متر" },
      { id: "M2", name: "Clamp", quantity: 4, unit: "قطعة" },
    ],
    feedback: [
      {
        id: "F1",
        byId: "U-INS1",
        byName: "عمر (فني مد)",
        role: "installer",
        message: "لا يوجد مشاكل - جاهز للتفعيل",
        kind: "info",
        createdAt: new Date().toISOString(),
      },
    ],
    history: [
      hist("ليث المبيعات", "إنشاء العقد", 3),
      hist("خالد الموزّع", "إسناد المهمة لفني المد عمر", 2),
      hist("عمر (فني مد)", "إنهاء المد وإدخال الكميات", 1),
    ],
  },
  {
    id: "INT086795901",
    customerName: "رنا فايز القضاة",
    phone: "0791778821",
    nationalId: "9970099812",
    area: "إربد / حي الصحة",
    service: "New Network Access",
    month: "Apr-26",
    lat: 32.5519,
    lng: 35.8471,
    status: "spliced",
    createdAt: new Date().toISOString(),
    deviceType: "ONT - Huawei HG8145V5",
    speed: "100 Mbps",
    createdById: "U-SALES",
    createdByName: "ليث المبيعات",
    assignedInstallerId: "U-INS2",
    assignedSplicerId: "U-SPL1",
    materials: [
      { id: "M1", name: "كابل Drop", quantity: 80, unit: "متر" },
      { id: "M2", name: "Connector", quantity: 2, unit: "قطعة" },
    ],
    feedback: [],
    history: [
      hist("ليث المبيعات", "إنشاء العقد", 5),
      hist("خالد الموزّع", "إسناد المد لسامي", 4),
      hist("سامي (فني مد)", "إنهاء المد", 3),
      hist("خالد الموزّع", "إسناد اللحام لياسر", 2),
      hist("ياسر (فني لحام)", "إنهاء اللحام", 1),
    ],
  },
  {
    id: "INT086796033",
    customerName: "سامر وليد بني هاني",
    phone: "0799334567",
    nationalId: "9960087712",
    area: "إربد / حي الصحة",
    service: "Fiber Upgrade",
    month: "Mar-26",
    lat: 32.5562,
    lng: 35.8527,
    status: "activated",
    createdAt: new Date().toISOString(),
    deviceType: "ONT - Huawei HG8145V5",
    speed: "100 Mbps",
    createdById: "U-SALES",
    createdByName: "ليث المبيعات",
    assignedInstallerId: "U-INS1",
    assignedSplicerId: "U-SPL2",
    materials: [{ id: "M1", name: "كابل Drop", quantity: 45, unit: "متر" }],
    feedback: [],
    activation: { username: "int086796033@fiber.jo", password: "Fb-7723xq", online: true, at: new Date().toISOString() },
    history: [
      hist("ليث المبيعات", "إنشاء العقد", 7),
      hist("سامي (فني مد)", "إنهاء المد", 5),
      hist("محمود (فني لحام)", "إنهاء اللحام", 3),
      hist("نور (تفعيل)", "تحويل الاشتراك إلى Online", 1),
    ],
  },
  {
    id: "INT086796120",
    customerName: "هبة عماد الطراونة",
    phone: "0795001234",
    nationalId: "9955123400",
    area: "إربد / حي الصحة",
    service: "New Network Access",
    month: "Mar-26",
    lat: 32.5588,
    lng: 35.8462,
    status: "approved",
    createdAt: new Date().toISOString(),
    deviceType: "ONT - Huawei HG8145V5",
    speed: "100 Mbps",
    createdById: "U-SALES",
    createdByName: "ليث المبيعات",
    assignedInstallerId: "U-INS2",
    assignedSplicerId: "U-SPL1",
    materials: [{ id: "M1", name: "كابل Drop", quantity: 55, unit: "متر" }],
    feedback: [],
    activation: { username: "int086796120@fiber.jo", password: "Fb-1192kd", online: true, at: new Date().toISOString() },
    supervisorApproved: true,
    history: [
      hist("ليث المبيعات", "إنشاء العقد", 10),
      hist("سامي (فني مد)", "إنهاء المد", 8),
      hist("ياسر (فني لحام)", "إنهاء اللحام", 6),
      hist("نور (تفعيل)", "تحويل إلى Online", 4),
      hist("أحمد مشرف المنطقة", "الكشف النهائي والموافقة", 2),
    ],
  },
  {
    id: "INT086796288",
    customerName: "خالد ناصر السرحان",
    phone: "0790887766",
    nationalId: "9945667712",
    area: "إربد / حي الصحة",
    service: "New Network Access",
    month: "May-26",
    lat: 32.5535,
    lng: 35.8499,
    status: "new",
    createdAt: new Date().toISOString(),
    deviceType: "ONT - Huawei HG8145V5",
    speed: "100 Mbps",
    createdById: "U-SALES",
    createdByName: "ليث المبيعات",
    assignedInstallerId: "U-INS1",
    materials: [],
    feedback: [
      {
        id: "F2",
        byId: "U-INS1",
        byName: "عمر (فني مد)",
        role: "installer",
        message: "بحاجة إلى كشف مشرف منطقة لإيجاد طريقة للمد",
        kind: "issue",
        createdAt: new Date().toISOString(),
      },
    ],
    history: [
      hist("ليث المبيعات", "إنشاء العقد", 2),
      hist("خالد الموزّع", "إسناد المد لعمر", 1),
      hist("عمر (فني مد)", "إرسال فيدباك: بحاجة كشف مشرف", 0),
    ],
  },
  {
    id: "INT086796350",
    customerName: "ليلى محمود الزعبي",
    phone: "0796553311",
    nationalId: "9938120055",
    area: "إربد / حي الصحة",
    service: "Fiber Upgrade",
    month: "May-26",
    lat: 32.5556,
    lng: 35.8508,
    status: "laid",
    createdAt: new Date().toISOString(),
    deviceType: "ONT - Huawei HG8145V5",
    speed: "100 Mbps",
    createdById: "U-SALES",
    createdByName: "ليث المبيعات",
    assignedInstallerId: "U-INS2",
    materials: [{ id: "M1", name: "كابل Drop", quantity: 70, unit: "متر" }],
    feedback: [],
    history: [
      hist("ليث المبيعات", "إنشاء العقد", 4),
      hist("خالد الموزّع", "إسناد المد لسامي", 3),
      hist("سامي (فني مد)", "إنهاء المد", 1),
    ],
  },
]

export const INITIAL_AREAS: AreaPrep[] = [
  {
    id: "AR-1",
    name: "حي الصحة - إربد",
    stages: [
      { key: "survey", label: "كشف ميداني للموقع", done: true },
      { key: "define", label: "تحديد المنطقة المراد خدمتها", done: true },
      { key: "poles", label: "توزيع الأعمدة والـ DBs", done: true },
      { key: "power", label: "التأكد من وصول الـ Power لجميع الـ DBs", done: false },
      { key: "handover", label: "تسليم المنطقة بعد التشييك", done: false },
    ],
    dbs: [
      { id: "DB-01", name: "DB-01", hasPower: true, splitterCount: 2, full: false },
      { id: "DB-02", name: "DB-02", hasPower: true, splitterCount: 1, full: false },
      { id: "DB-03", name: "DB-03", hasPower: false, splitterCount: 1, full: false },
      { id: "DB-04", name: "DB-04", hasPower: true, splitterCount: 2, full: true },
    ],
  },
]
